version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_bin'
      - '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=project
    restart: always

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui%

  laptop:
    image: kvasilev96/laptop:v1
    depends_on: [db]

    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=12345
